name: Trigger Spring Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Spring Job
        uses: appleboy/jenkins-action@v0.0.2
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_API_TOKEN }}
          job: 'spring-pipeline'
